#!/bin/sh

python manage.py loaddata ./er/fixtures/initial_groups.json
python manage.py loaddata ./er/fixtures/initial_documents.json

# author fixtures are now included in initial_documents
# AUTHOR_FIXTURE_FILE=./er/fixtures/initial_authors.json
# if [ -f $AUTHOR_FIXTURE_FILE ]; then
#     python manage.py loaddata $AUTHOR_FIXTURE_FILE
# fi

